server {
    listen 80;
    server_name anmaai.cn www.anmaai.cn;

    root /var/www/anmaai.cn;
    index index.html;

    client_max_body_size 1024m;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(mp4|webm|mov|m4v)$ {
        add_header Accept-Ranges bytes;
        expires 30d;
        access_log off;
        try_files $uri =404;
    }

    location ~* \.(css|js)$ {
        expires 5m;
        add_header Cache-Control "public, max-age=300";
        access_log off;
        try_files $uri =404;
    }

    location ~* \.(png|jpg|jpeg|gif|webp|avif|css|js|ttf|woff|woff2)$ {
        expires 30d;
        access_log off;
        try_files $uri =404;
    }
}
